version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sdn1364
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fridgy
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
